[package]
name = "lyrac"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lyra-meta = { path = "../../crates/lyra-meta" }
lyra-driver = { path = "../../crates/lyra-driver" }
clap.workspace = true
anyhow.workspace = true

