[package]
name = "compiler"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
lyra-meta = { path = "../crates/lyra-meta" }
anyhow.workspace = true
thiserror.workspace = true

